// <auto-generated />
using System;
using CatalogService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogServiceContext))]
    [Migration("20240311153541_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Domain.Entities.ChiTietLinhVucXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diem")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Dieu")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Khoan")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("LinhVucXuPhatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinhVucXuPhatId");

                    b.ToTable("ChiTietLinhVucXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ChiTietQuyetDinhXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DieuKhoanDiemBoSungId")
                        .HasColumnType("int");

                    b.Property<int>("DieuKhoanKhacPhucId")
                        .HasColumnType("int");

                    b.Property<int>("DieuThiHanhId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KhoanDiemThiHanhId")
                        .HasColumnType("int");

                    b.Property<int>("LinhVucXuPhatId")
                        .HasColumnType("int");

                    b.Property<long>("MucPhat")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("QuyDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuyetDinhXuPhatId")
                        .HasColumnType("int");

                    b.Property<int>("TinhTietId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuyetDinhXuPhatId");

                    b.ToTable("ChiTietQuyetDinhXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CoQuanBanHanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NhomCoQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenCoQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CoQuanBanHanh", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DanhMucDinhDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaDinhDanhTCVN")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Website")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucDinhDanh", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diem")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Dieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("LinhVucXuPhatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinhVucXuPhatId");

                    b.ToTable("DieuKhoanXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.GiayPhepTamGiu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoXuLyViPhamId");

                    b.ToTable("GiayPhepTamGiu", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HinhThucXuPhatBoSung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("HinhThucXuPhatBoSung", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HinhThucXuPhatChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("HinhThucXuPhatChinh", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HoSoXuLyViPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HanhViViPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("MaHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHoSo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HoSoXuLyViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LinhVucXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DanChungNghiDinh")
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("HanhVi_QuyetDinh")
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("HetHieuLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("HienThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<int?>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NghiDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NhomLinhVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoXuLyViPhamId");

                    b.ToTable("LinhVucXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LoaiVanBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("LoaiVanBan", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuanHuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DanhMucDinhDanhId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhThanhPhoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucDinhDanhId");

                    b.HasIndex("TinhThanhPhoId");

                    b.ToTable("QuanHuyen", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuyetDinhXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienPhapKhacPhucHauQua")
                        .HasColumnType("int");

                    b.Property<string>("BienPhapKhacPhucHauQuaCuThe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CanCuQuyDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CanCuVanBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("CoQuanBanHanhId")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiemViPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DoiTuongViPhamId")
                        .HasColumnType("int");

                    b.Property<string>("DoiTuongViPhamKhac")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViPhoiHopThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("HieuLucThiHanhNgay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HinhThucXuPhatBoSung")
                        .HasColumnType("int");

                    b.Property<string>("HinhThucXuPhatBoSungCuThe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HinhThucXuPhatChinh")
                        .HasColumnType("int");

                    b.Property<string>("HinhThucXuPhatCuThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDoiTuongViPham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhapQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiRaQuyetDinhId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungLienQuanKhacPhucHauQua")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NoiNopTienPhat")
                        .HasColumnType("int");

                    b.Property<string>("NoiNopTienPhatTuNhap")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiThucHien")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("SoTienPhat")
                        .HasColumnType("bigint");

                    b.Property<string>("SoTienPhatBangChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ThoiHanKhacPhucHauQua")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiHanThucHienXuPhatBoSung")
                        .HasColumnType("int");

                    b.Property<long?>("TienKhacPhuc")
                        .HasColumnType("bigint");

                    b.Property<long?>("TienTruyThu")
                        .HasColumnType("bigint");

                    b.Property<string>("TinhTietGiamNhe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhTietTangNang")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CoQuanBanHanhId");

                    b.HasIndex("HoSoXuLyViPhamId");

                    b.ToTable("QuyetDinhXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TangVatPhuongTienTamGiu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChungLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoXuLyViPhamId");

                    b.ToTable("TangVatPhuongTienTamGiu", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ThamQuyenXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DieuKhoanXuPhatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("ThamQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("DieuKhoanXuPhatId");

                    b.ToTable("ThamQuyenXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TinhThanhPho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TinhThanhPho", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanGiaiQuyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaGiayTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenGiayTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TheoNghiDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("VanBanGiaiQuyet", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanLienQuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayBanHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VanBanPhapLuatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VanBanPhapLuatId");

                    b.ToTable("VanBanLienQuan", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanPhapLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoQuanBanHanhId")
                        .HasColumnType("int");

                    b.Property<string>("DuongDanUrl")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LoaiVanBanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBanHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("SoHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("TrichYeuNoiDung")
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CoQuanBanHanhId");

                    b.HasIndex("LoaiVanBanId");

                    b.ToTable("VanBanPhapLuat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.XaPhuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuanHuyenId");

                    b.ToTable("XaPhuong", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ChiTietLinhVucXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.LinhVucXuPhat", "LinhVucXuPhat")
                        .WithMany("ChiTietLinhVucXuPhat")
                        .HasForeignKey("LinhVucXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVucXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ChiTietQuyetDinhXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.QuyetDinhXuPhat", "QuyetDinhXuPhat")
                        .WithMany("ChiTietQuyetDinhXuPhats")
                        .HasForeignKey("QuyetDinhXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuyetDinhXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.LinhVucXuPhat", "LinhVucXuPhat")
                        .WithMany()
                        .HasForeignKey("LinhVucXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVucXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.GiayPhepTamGiu", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.HoSoXuLyViPham", "HoSoXuLyViPham")
                        .WithMany()
                        .HasForeignKey("HoSoXuLyViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoXuLyViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LinhVucXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.HoSoXuLyViPham", null)
                        .WithMany("LinhVucXuPhats")
                        .HasForeignKey("HoSoXuLyViPhamId");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuanHuyen", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.DanhMucDinhDanh", null)
                        .WithMany("QuanHuyen")
                        .HasForeignKey("DanhMucDinhDanhId");

                    b.HasOne("CatalogService.Domain.Entities.TinhThanhPho", "TinhThanhPho")
                        .WithMany("QuanHuyen")
                        .HasForeignKey("TinhThanhPhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanhPho");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuyetDinhXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.CoQuanBanHanh", "CoQuanBanHanh")
                        .WithMany()
                        .HasForeignKey("CoQuanBanHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.HoSoXuLyViPham", "HoSoXuLyViPham")
                        .WithMany()
                        .HasForeignKey("HoSoXuLyViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoQuanBanHanh");

                    b.Navigation("HoSoXuLyViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TangVatPhuongTienTamGiu", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.HoSoXuLyViPham", "HoSoXuLyViPham")
                        .WithMany("TangVatPhuongTienTamGius")
                        .HasForeignKey("HoSoXuLyViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoXuLyViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ThamQuyenXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.DieuKhoanXuPhat", "DieuKhoanXuPhat")
                        .WithMany("ThamQuyenXuPhats")
                        .HasForeignKey("DieuKhoanXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DieuKhoanXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanLienQuan", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.VanBanPhapLuat", "VanBanPhapLuat")
                        .WithMany("VanBanLienQuan")
                        .HasForeignKey("VanBanPhapLuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VanBanPhapLuat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanPhapLuat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.CoQuanBanHanh", "CoQuanBanHanh")
                        .WithMany("VanBanPhapLuat")
                        .HasForeignKey("CoQuanBanHanhId");

                    b.HasOne("CatalogService.Domain.Entities.LoaiVanBan", "LoaiVanBan")
                        .WithMany("VanBanPhapLuat")
                        .HasForeignKey("LoaiVanBanId");

                    b.Navigation("CoQuanBanHanh");

                    b.Navigation("LoaiVanBan");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.XaPhuong", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("XaPhuong")
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CoQuanBanHanh", b =>
                {
                    b.Navigation("VanBanPhapLuat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DanhMucDinhDanh", b =>
                {
                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanXuPhat", b =>
                {
                    b.Navigation("ThamQuyenXuPhats");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HoSoXuLyViPham", b =>
                {
                    b.Navigation("LinhVucXuPhats");

                    b.Navigation("TangVatPhuongTienTamGius");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LinhVucXuPhat", b =>
                {
                    b.Navigation("ChiTietLinhVucXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LoaiVanBan", b =>
                {
                    b.Navigation("VanBanPhapLuat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuanHuyen", b =>
                {
                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuyetDinhXuPhat", b =>
                {
                    b.Navigation("ChiTietQuyetDinhXuPhats");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TinhThanhPho", b =>
                {
                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanPhapLuat", b =>
                {
                    b.Navigation("VanBanLienQuan");
                });
#pragma warning restore 612, 618
        }
    }
}
