// <auto-generated />
using System;
using CatalogService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatalogService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogServiceContext))]
    partial class CatalogServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Domain.Entities.ChiTietLinhVucXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diem")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Dieu")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Khoan")
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("LinhVucXuPhatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinhVucXuPhatId");

                    b.ToTable("ChiTietLinhVucXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CoQuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapCoQuan")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("SoFax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCoQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CoQuan", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CoQuanBanHanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NhomCoQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenCoQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CoQuanBanHanh", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CongDan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DanToc")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocVan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LoaiGiayToDinhDanh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NgheNghiep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiLamViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoLoaiGiayTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenGoiKhac")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CongDan", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DanhMucDinhDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaDinhDanhTCVN")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Website")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucDinhDanh", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanBoSungKhacPhuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diem")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Dieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("DieuKhoanXuPhatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("LoaiDieuKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DieuKhoanXuPhatId");

                    b.ToTable("DieuKhoanBoSungKhacPhuc", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Diem")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Dieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Khoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("LinhVucXuPhatId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LinhVucXuPhatId");

                    b.ToTable("DieuKhoanXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.GiayPhepTamGiu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoXuLyViPhamId");

                    b.ToTable("GiayPhepTamGiu", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HSXLVP_VanBanGiaiQuyet", b =>
                {
                    b.Property<int>("HoSoXuLyViPhamId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("VanBanGiaiQuyetId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HoSoXuLyViPhamId", "VanBanGiaiQuyetId");

                    b.HasIndex("VanBanGiaiQuyetId");

                    b.ToTable("HSXLVP_VanBanGiaiQuyets");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HanhViViPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChiTietHSXLVPVVBGQId")
                        .HasColumnType("int");

                    b.Property<int?>("DieuKhoanBoSungId")
                        .HasColumnType("int");

                    b.Property<int?>("DieuKhoanKhacPhucId")
                        .HasColumnType("int");

                    b.Property<int>("DieuKhoanXuPhatId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<int>("LinhVucXuPhatId")
                        .HasColumnType("int");

                    b.Property<long>("MucPhat")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("QuyDinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuyetDinhXuPhatId")
                        .HasColumnType("int");

                    b.Property<int>("TinhTietViPham")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DieuKhoanXuPhatId");

                    b.HasIndex("QuyetDinhXuPhatId");

                    b.ToTable("HanhViViPham", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HinhThucXuPhatBoSung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("HinhThucXuPhatBoSung", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HinhThucXuPhatChinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("HinhThucXuPhatChinh", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HoSoXuLyViPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CaNhanViPhamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCaNhanViPhamKhac")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiVuViecViPham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHoSo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("SoHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenHoSo")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ThongTinKhac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhTietViPham")
                        .HasColumnType("int");

                    b.Property<int>("TrangThaiHoSoViPham")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HoSoXuLyViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LinhVucXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DanChungNghiDinh")
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("HanhVi_QuyetDinh")
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("HetHieuLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<bool>("HienThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NghiDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NhomLinhVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLinhVuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("LinhVucXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LoaiVanBan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("LoaiVanBan", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuanHuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DanhMucDinhDanhId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TinhThanhPhoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucDinhDanhId");

                    b.HasIndex("TinhThanhPhoId");

                    b.ToTable("QuanHuyen", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuyetDinhXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BienPhapKhacPhucHauQua")
                        .HasColumnType("int");

                    b.Property<string>("BienPhapKhacPhucHauQuaCuThe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CanCuQuyDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CanCuVanBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("CoQuanBanHanhId")
                        .HasColumnType("int");

                    b.Property<string>("DiaDiemViPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("DoiTuongViPhamId")
                        .HasColumnType("int");

                    b.Property<string>("DoiTuongViPhamKhac")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViPhoiHopThucHien")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("HieuLucThiHanhNgay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HinhThucXuPhatBoSung")
                        .HasColumnType("int");

                    b.Property<string>("HinhThucXuPhatBoSungCuThe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HinhThucXuPhatChinh")
                        .HasColumnType("int");

                    b.Property<string>("HinhThucXuPhatCuThe")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LoaiDoiTuongViPham")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayNhapQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<Guid>("NguoiRaQuyetDinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungLienQuanKhacPhucHauQua")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NoiNopTienPhat")
                        .HasColumnType("int");

                    b.Property<string>("NoiNopTienPhatTuNhap")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NoiThucHien")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("SoTienPhat")
                        .HasColumnType("bigint");

                    b.Property<string>("SoTienPhatBangChu")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ThoiHanKhacPhucHauQua")
                        .HasColumnType("int");

                    b.Property<int?>("ThoiHanThucHienXuPhatBoSung")
                        .HasColumnType("int");

                    b.Property<long?>("TienKhacPhuc")
                        .HasColumnType("bigint");

                    b.Property<long?>("TienTruyThu")
                        .HasColumnType("bigint");

                    b.Property<string>("TinhTietGiamNhe")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhTietTangNang")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CoQuanBanHanhId");

                    b.HasIndex("DoiTuongViPhamId");

                    b.ToTable("QuyetDinhXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TangVatPhuongTienTamGiu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChungLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("HoSoXuLyViPhamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoXuLyViPhamId");

                    b.ToTable("TangVatPhuongTienTamGiu", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ThamQuyenXuPhat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DieuKhoanXuPhatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("ThamQuyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("DieuKhoanXuPhatId");

                    b.ToTable("ThamQuyenXuPhat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TinhThanhPho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("TinhThanhPho", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ToChuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucDanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiayPhepSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("MaSo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayGiayPhep")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NoiCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoChungNhan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ToChuc", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanGiaiQuyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaGiayTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenGiayTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TheoNghiDinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("VanBanGiaiQuyet", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanLienQuan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayBanHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("VanBanPhapLuatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VanBanPhapLuatId");

                    b.ToTable("VanBanLienQuan", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanPhapLuat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoQuanBanHanhId")
                        .HasColumnType("int");

                    b.Property<string>("DuongDanUrl")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("LoaiVanBanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBanHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayHieuLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("SoHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("TrichYeuNoiDung")
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("CoQuanBanHanhId");

                    b.HasIndex("LoaiVanBanId");

                    b.ToTable("VanBanPhapLuat", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.XaPhuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<string>("MaDinhDanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhatCuoi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiCapNhatCuoi")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<int>("QuanHuyenId")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuanHuyenId");

                    b.ToTable("XaPhuong", (string)null);
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ChiTietLinhVucXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.LinhVucXuPhat", "LinhVucXuPhat")
                        .WithMany("ChiTietLinhVucXuPhat")
                        .HasForeignKey("LinhVucXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVucXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanBoSungKhacPhuc", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.DieuKhoanXuPhat", "DieuKhoanXuPhat")
                        .WithMany("DieuKhoanBoSungKhacPhucs")
                        .HasForeignKey("DieuKhoanXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DieuKhoanXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.LinhVucXuPhat", "LinhVucXuPhat")
                        .WithMany()
                        .HasForeignKey("LinhVucXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LinhVucXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.GiayPhepTamGiu", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.HoSoXuLyViPham", "HoSoXuLyViPham")
                        .WithMany()
                        .HasForeignKey("HoSoXuLyViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoXuLyViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HSXLVP_VanBanGiaiQuyet", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.HoSoXuLyViPham", "HoSoXuLyViPham")
                        .WithMany("HSXLVP_VanBanGiaiQuyets")
                        .HasForeignKey("HoSoXuLyViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.VanBanGiaiQuyet", "VanBanGiaiQuyet")
                        .WithMany("HSXLVP_VanBanGiaiQuyets")
                        .HasForeignKey("VanBanGiaiQuyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoXuLyViPham");

                    b.Navigation("VanBanGiaiQuyet");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HanhViViPham", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.DieuKhoanXuPhat", "DieuKhoanXuPhat")
                        .WithMany()
                        .HasForeignKey("DieuKhoanXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.QuyetDinhXuPhat", null)
                        .WithMany("HanhViViPhams")
                        .HasForeignKey("QuyetDinhXuPhatId");

                    b.Navigation("DieuKhoanXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuanHuyen", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.DanhMucDinhDanh", null)
                        .WithMany("QuanHuyen")
                        .HasForeignKey("DanhMucDinhDanhId");

                    b.HasOne("CatalogService.Domain.Entities.TinhThanhPho", "TinhThanhPho")
                        .WithMany("QuanHuyen")
                        .HasForeignKey("TinhThanhPhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TinhThanhPho");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuyetDinhXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.CoQuanBanHanh", "CoQuanBanHanh")
                        .WithMany()
                        .HasForeignKey("CoQuanBanHanhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Domain.Entities.CongDan", "DoiTuongViPham")
                        .WithMany("QuyetDinhXuPhats")
                        .HasForeignKey("DoiTuongViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoQuanBanHanh");

                    b.Navigation("DoiTuongViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TangVatPhuongTienTamGiu", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.HoSoXuLyViPham", "HoSoXuLyViPham")
                        .WithMany("TangVatPhuongTienTamGius")
                        .HasForeignKey("HoSoXuLyViPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoXuLyViPham");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.ThamQuyenXuPhat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.DieuKhoanXuPhat", "DieuKhoanXuPhat")
                        .WithMany("ThamQuyenXuPhats")
                        .HasForeignKey("DieuKhoanXuPhatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DieuKhoanXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanLienQuan", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.VanBanPhapLuat", "VanBanPhapLuat")
                        .WithMany("VanBanLienQuan")
                        .HasForeignKey("VanBanPhapLuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VanBanPhapLuat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanPhapLuat", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.CoQuanBanHanh", "CoQuanBanHanh")
                        .WithMany("VanBanPhapLuat")
                        .HasForeignKey("CoQuanBanHanhId");

                    b.HasOne("CatalogService.Domain.Entities.LoaiVanBan", "LoaiVanBan")
                        .WithMany("VanBanPhapLuat")
                        .HasForeignKey("LoaiVanBanId");

                    b.Navigation("CoQuanBanHanh");

                    b.Navigation("LoaiVanBan");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.XaPhuong", b =>
                {
                    b.HasOne("CatalogService.Domain.Entities.QuanHuyen", "QuanHuyen")
                        .WithMany("XaPhuong")
                        .HasForeignKey("QuanHuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CoQuanBanHanh", b =>
                {
                    b.Navigation("VanBanPhapLuat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.CongDan", b =>
                {
                    b.Navigation("QuyetDinhXuPhats");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DanhMucDinhDanh", b =>
                {
                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.DieuKhoanXuPhat", b =>
                {
                    b.Navigation("DieuKhoanBoSungKhacPhucs");

                    b.Navigation("ThamQuyenXuPhats");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.HoSoXuLyViPham", b =>
                {
                    b.Navigation("HSXLVP_VanBanGiaiQuyets");

                    b.Navigation("TangVatPhuongTienTamGius");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LinhVucXuPhat", b =>
                {
                    b.Navigation("ChiTietLinhVucXuPhat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.LoaiVanBan", b =>
                {
                    b.Navigation("VanBanPhapLuat");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuanHuyen", b =>
                {
                    b.Navigation("XaPhuong");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.QuyetDinhXuPhat", b =>
                {
                    b.Navigation("HanhViViPhams");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.TinhThanhPho", b =>
                {
                    b.Navigation("QuanHuyen");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanGiaiQuyet", b =>
                {
                    b.Navigation("HSXLVP_VanBanGiaiQuyets");
                });

            modelBuilder.Entity("CatalogService.Domain.Entities.VanBanPhapLuat", b =>
                {
                    b.Navigation("VanBanLienQuan");
                });
#pragma warning restore 612, 618
        }
    }
}
