global:
  scrape_interval: 5s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"
      
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  # Add configurations to scrape metrics from your services
  - job_name: 'coreservice_metrics'
    static_configs:
      - targets: ['coreservice.api:80']
  
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  
  - job_name: "cadvisor"
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: "A"
        port: 8080

    static_configs:
      - targets: ["cadvisor:8080"]
