version: '3'

services:
  mssql-server:
    container_name: mssql-server
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "5434:1433"
    networks:
      - qlvphc-network

  # coreservice.api:
  #   container_name: coreservice.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;
  #   ports:
  #     - "5101:80"
  #   # volumes:
  #   #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #   #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #   networks:
  #    - qlvphc-network

  catalogservice.api:
    container_name: catalogservice.api
    ports:
      - "5102:80"
    depends_on:
      - identityservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - ConnectionStrings:DefaultConnectionString=Server=mssql-server;Database=qlvphc.catalog;User=sa;Password=YourStrong@Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=true
      - IDENTITY_API_URL=http://identityservice.api:5104/api/User
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - qlvphc-network

  identityservice.api:
    container_name: identityservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      - ConnectionStrings:DefaultConnection=Server=mssql-server;Database=qlvphc.identity;User=sa;Password=YourStrong@Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=true

    ports:
      - "5104:80"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro'
    depends_on:
      - mssql-server
    networks:
      - qlvphc-network

  # reportservice.api:
  #   container_name: reportservice.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;
  #   ports:
  #     - "5103:80"
  #   # volumes:
  #   #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #   #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #   networks:
  #    - qlvphc-network

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  # ocelotapigateway:
  #   container_name: ocelotapigateway
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;
  #   depends_on:
  #     - coreservice.api
  #     - catalogservice.api
  #     - identityservice.api
  #     - reportservice.api
  #   ports:
  #     - "5200:80"
  #   networks:
  #    - qlvphc-network