version: '3.3'

services:
  mssql-server:
    container_name: mssql-server
    environment:
      - SA_PASSWORD=YourStrong@Passw0rd
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
     - qlvphc-network

  # coreservice.api:
  #   container_name: coreservice.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;
  #   ports:
  #     - "5101:80"
  #   # volumes:
  #   #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #   #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #   networks:
  #    - qlvphc-network

  catalogservice.api:
    container_name: catalogservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
    ports:
      - "5102:5102"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
     - qlvphc-network

  identityservice.api:
    container_name: identityservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;
      # - ConnectionString=Server=mssql-server;Database=QLVPHC;User=sa;Password=Abc@@123;MultipleActiveResultSets=true;TrustServerCertificate=true

    ports:
      - "5104:5104"
    # volumes:
    #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
    #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro'
    depends_on:
      - mssql-server
    networks:
     - qlvphc-network

  # reportservice.api:
  #   container_name: reportservice.api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;
  #   ports:
  #     - "5103:80"
  #   # volumes:
  #   #   - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #   #   - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #   networks:
  #    - qlvphc-network

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  # ocelotapigateway:
  #   container_name: ocelotapigateway
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80;
  #   depends_on:
  #     - coreservice.api
  #     - catalogservice.api
  #     - identityservice.api
  #     - reportservice.api
  #   ports:
  #     - "5200:80"
  #   networks:
  #    - qlvphc-network