version: '3.8'

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Tuandeptrai" # Change this password
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
